# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Install system dependencies for opencv
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libgl1 \
        libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

# Set work directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies and the MCP server
RUN pip install --no-cache-dir .

# Default entrypoint for stdio MCP server
ENTRYPOINT ["mcp-sticky"]
